const skillsData = [
  "Agile Development",
  "Android Development",
  "API Design",
  "App Deployment",
  "App Store Optimization",
  "Authentication & Authorization",
  "AWS",
  "Azure",
  "Bash Scripting",
  "Backend Development",
  "C",
  "C#",
  "C++",
  "CI/CD Pipelines",
  "Cloud Functions",
  "Cloud Storage",
  "Cloudflare",
  "Containerization",
  "CSS3",
  "Dart",
  "Data Engineering",
  "Data Modeling",
  "Data Structures",
  "Database Design",
  "Deno",
  "DevOps",
  "Django",
  "Docker",
  "ElasticSearch",
  "Electron.js",
  "Express.js",
  "Figma to Code",
  "Firebase",
  "Flutter",
  "Frontend Development",
  "Game Engines",
  "Game Physics",
  "Game UI Design",
  "Game Development",
  "Git",
  "GitHub Actions",
  "Go (Golang)",
  "Google Cloud Platform (GCP)",
  "GraphQL",
  "gRPC",
  "HTML5",
  "iOS Development",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jest",
  "Kafka",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Linux Server Management",
  "Machine Learning",
  "Microservices Architecture",
  "MongoDB",
  "MySQL",
  "Natural Language Processing (NLP)",
  "Neural Networks",
  "Next.js",
  "Node.js",
  "NoSQL Databases",
  "NPM/Yarn",
  "OAuth2",
  "Objective-C",
  "OpenCV",
  "OpenGL",
  "ORMs (Prisma, Sequelize, Mongoose)",
  "PHP",
  "PostgreSQL",
  "Progressive Web Apps (PWA)",
  "Python",
  "Quantum Computing (Basic)",
  "R",
  "React",
  "React Native",
  "Redis",
  "Redux",
  "REST API",
  "Ruby on Rails",
  "SASS",
  "Security Best Practices",
  "Serverless Architecture",
  "Socket.io",
  "SQL",
  "Stripe Integration",
  "Supabase",
  "Swagger/OpenAPI",
  "Swift",
  "Tailwind CSS",
  "TensorFlow",
  "Testing Libraries (Jest, Mocha, Cypress)",
  "Three.js",
  "TypeScript",
  "UI/UX Principles",
  "Unity",
  "Vercel",
  "Version Control (Git)",
  "Vite",
  "VitePress",
  "Vue.js",
  "Web Accessibility (a11y)",
  "Web Animation",
  "Web Security",
  "Web Sockets",
  "Webpack",
  "Zustand"
];



export default skillsData